### ISSUE TITLE
Veruscoin Implementation 

### ISSUE THREAD

**Issue by cimam95** [xiaolin1579/miningcore#14]
Hi @xiaolin1579 would you be able to assist with Veruscoin implementation for Mining core?

Things such as code for coins.json Veruscoin.conf(daemon conf) and the code for  pool conf?

**Comment by theodufort** [comment]
Hey @cimam95 , I wanted myself to implement Zephyr (ZEPH) but I think the list they provide is more of an "official" supported coin list.

Because from [this video of the mining core setup](https://www.youtube.com/watch?v=Ns45-OuHc_k&t=909s&ab_channel=RetroMikeTech) he uses Pigeoncoin which is not in the list and successfully does it.

**Comment by cimam95** [comment]
> Hey @cimam95 , I wanted myself to implement Zephyr (ZEPH) but I think the list they provide is more of an "official" supported coin list.
> 
> Because from [this video of the mining core setup](https://www.youtube.com/watch?v=Ns45-OuHc_k&t=909s&ab_channel=RetroMikeTech) he uses Pigeoncoin which is not in the list and successfully does it.

Hey @theodufort  that video is a great starting point,  but it doesn't cover more advanced stuff which you will have to learn by trial and error and also going through different repos. I'm working on implementing Zephyr and Veruscoin right now which is more challenging than expected.

**Comment by cimam95** [comment]
Verus coin added thanks to https://github.com/blackmennewstyle/miningcore/discussions/3

Closing thread.

**Comment by theodufort** [comment]
@cimam95 what about Zephyr? Im willing to collaborate on it if you are willing

**Comment by xiaolin1579** [comment]
https://github.com/xiaolin1579/miningcore/commit/4252dac4822a18d4c1e9d3ac9e80ae9d1396f92e
