### ISSUE TITLE
Pool+Miners Hashrate is not accurate !!!

### ISSUE THREAD

**Issue by b2d2dbone** [xiaolin1579/miningcore#16]
Hi Xiaolin  ))

What is the optimal difficulty for groestlcoin ?

This is my configs 

"difficulty": 8000,    

           "varDiff": { "minDiff": 1000, "maxDiff": 50000, "targetTime": 5, "retargetTime": 30, "variancePercent": 50, "maxDelta": 1 } 
           
    

   I used many values and the Hashrate is never accurate very low I rented 10GH/s and 20GH/s  rigs and the Hashrate reported  
   is below 1GH/s   
           
   any ideas ?

**Comment by xiaolin1579** [comment]
maybe try change
https://github.com/xiaolin1579/miningcore/blob/6b9c0e1646e7de5cbd19eb80f22cc8501cbbd40c/src/Miningcore/coins.json#L1548

**Comment by b2d2dbone** [comment]
I will try to increase it till I get more accurate result and post shareMultiplier values here

**Comment by xiaolin1579** [comment]
try change to 256

**Comment by b2d2dbone** [comment]
Great the after using 256 the hashrate seems to be more accurate  Thanks dear
could pls tell 
so 
I created  datebase miningcore with user minincore  etc and imported "createdb.sql 
from 
/miningcore/src/Miningcore/Persistence/Postgres/Scripts  
 I see 
 add_minereffort.sql  cleandb.sql  createdb.sql  createdb_postgresql_11_appendix.sql  legacy_timestamp_migration.sql
 
 I only imported  createdb.sql 
 
 and according to the repository requirements if I wanna use multi cluster   I should  make the shares table   list-partitioned table
 
 so I just // the cluster from my config.json
 
also in the config.json   there is " "shareRecoveryFile": "/app/ "shareRecoveryFile": 

how to access this path  and how to use this file "shareRecoveryFile" incase if anything goes wrong ?

The only thing I find in the repository is to pg_backup  should I just dumb the whole db and reimport it then !!

Thank you very much you really bringing life to this project .

**Comment by xiaolin1579** [comment]
add_minereffort.sql It may not be necessary for a new pool. because it has been added to createdb.sql
createdb_postgresql_11_appendix.sql legacy_timestamp_migration.sql should be used.

**Comment by b2d2dbone** [comment]
Ok Done good luck adding new algo + coins >> you can close this issue 

Have a nice day/night ))
