### ISSUE TITLE
Block 3003832 submission failed with: high-hash [ blockhash]

### ISSUE THREAD

**Issue by b2d2dbone** [xiaolin1579/miningcore#29]
Hi Xiaolin  

I got this warning on MAZACOIN 
 [W] [MAZA] Block 3004860 submission failed with: old-versionbits(0x09000000) 

I checked the pool wallet on block explorer it has some coins found by the pool  which means it has found a block 

meanwhile the pool UI shows no blocks found  or even orphaned  

for another coin ROGER
multiple blocks   found and submitted  but all of them are  orphaned 
logs shows :

classified as orphaned due to daemon error -5 

what should I do to skip this error ? 

thank you

**Comment by xiaolin1579** [comment]
need used address legacy type

**Comment by b2d2dbone** [comment]
Hi Xioalin thanks dear 
could share your miningcore.js webui  configs api and weburl parts I could not set  https am almost giving up 
last tutorial I tried was "https://blog.tekspace.io/how-to-setup-lets-encrypt-ssl-certificate-with-nginx-on-ubuntu-22-04/"
same thing only https index and http not working and the pool show the maintenance message

**Comment by b2d2dbone** [comment]
Hi Xioalin 
using legacy worked on ROGER but not for MAZA
after using legacy address am getting this error [MAZA] Block 3007619 submission failed with: high-hash ???

 thanks dear

**Comment by xiaolin1579** [comment]
> Hi Xioalin Do I have to use legacy on all coins ? using legacy worked on ROGER but not for MAZA after using legacy address am getting this error [MAZA] Block 3007619 submission failed with: high-hash ???
> 
> thanks dear

What algorithm for MAZA

**Comment by b2d2dbone** [comment]
> > Hi Xioalin Do I have to use legacy on all coins ? using legacy worked on ROGER but not for MAZA after using legacy address am getting this error [MAZA] Block 3007619 submission failed with: high-hash ???
> > thanks dear
> 
> What algorithm for MAZA

SHA256

**Comment by lurchinms** [comment]
maza coin does nbot support ASSIC Boost

**Comment by b2d2dbone** [comment]
> maza coin does support ASSIC Boost won't work on miningcore software

Thank you very much 
I noted that the latest  Maza Core dropped support for ASICBOOST "https://github.com/MazaCoin/maza/releases" so I tried older version MAZA v0.10.2 and I got the same issues
