### ISSUE TITLE
Found the issue of  Block submission failed with: bad-cb-payee

### ISSUE THREAD

**Issue by stabner** [xiaolin1579/miningcore#30]
I know this is not an "issue", i rather want to post this here so others with the same problem can spend their time better than i did looking for a solution to my previous problem.

The programmed coin in Coin.json file was wrong.  Add this line ---> "hasSmartNodes": true,

},
    "gspcoin": {
        "name": "Gsp Coin",
        "canonicalName": "GspCoin",
        "symbol": "GSPC",
        "family": "bitcoin",
        "website": "https://coin.globalsocialpost.com/",
        "market": "https://www.bitoreum.exchange/trading/gspcusdt",
        "twitter": "https://twitter.com/gspcoin",
        "discord": "https://discord.gg/Anh2sr4txV",
        "coinbaseHasher": {
            "hash": "sha256d"
        },
        "headerHasher": {
            "hash": "ghostrider"
        },
        "blockHasher": {
            "hash": "reverse",
            "args": [
                {
                    "hash": "sha256d"
                }
            ]
        },
        "hasFounderFee": true,
        "hasMasterNodes": true,
        "hasSmartNodes": true,
        "foundersRewardAddress": ["GZBNAiLokyYvSwNLftReXuYbvdmzNoorGj"],
        "shareMultiplier": 65536,
        "explorerBlockLink": "https://explorer.globalsocialpost.com/block/$height$",
        "explorerTxLink": "https://explorer.globalsocialpost.com/tx/{0}",
        "explorerAccountLink": "https://explorer.globalsocialpost.com/address/{0}"

**Comment by xiaolin1579** [comment]
https://github.com/xiaolin1579/miningcore/blob/dev/src/Miningcore/Blockchain/Bitcoin/BitcoinJob.cs#L789-L807

**Comment by xiaolin1579** [comment]
https://github.com/oliverw/miningcore/commit/5a6d69d56f16aa0638068a8e67fb4f3690a11619
