### ISSUE TITLE
Not processing found block on yerbas coin ghostrider algo

### ISSUE THREAD

**Issue by lurchinms** [xiaolin1579/miningcore#31]
[2023-12-06 17:04:34.7680] [I] [yerb] Daemon accepted block 405011 [bee6ac945efa016a4565a63dc89cbe5200d12b51f245d7a2a1dd3fe8aabe6f55] submitted by yhBodyyTbogdjZ7pZGF4ojJ3dtTgEGq5bP 

https://kriptokyng.com/coin/yerbas?blockID=yerb&coinSymbol=YERB

**Comment by lurchinms** [comment]
Also not working on Yenten either algo yescrypt

**Comment by lurchinms** [comment]
rebuild it twice and still no change

**Comment by b2d2dbone** [comment]
> Also not working on Yenten either algo yescrypt

all YTN founded blocks takes to much time to get confirmed I think it's something to do with the network it self
