### ISSUE TITLE
Mining $BEL Block submission failed

### ISSUE THREAD

**Issue by 0xInuarashi** [xiaolin1579/miningcore#34]
I'm Mining $BEL, a new (old) coin based on Litecoin by BillyM2K (dogecoin creator)

I set up miningcore with bells daemon using legacy settings, but block submission failed. This is the error:

Block XXX Submission failed with: Params must be an array!

Could you help out?

![image](https://github.com/xiaolin1579/miningcore/assets/88496996/4b8c597d-7722-4492-b9bd-4e3e73ea31fe)

**Comment by mboyd1** [comment]
can you share the coins.json config for this coin and any relevant legacy settings you mentioned
