### ISSUE TITLE
hashrate not accurate Aurum algo

### ISSUE THREAD

**Issue by 1NF1N18Y** [xiaolin1579/miningcore#51]
I use this as my config for the pool

        {
      "id": "waifucore",
      "enableInternalStratum": true,
      "enabled": true,
      "jobRebroadcastTimeout":90,
      "coin": "waifucore",
      "address": "",
      "rewardRecipients": [
        {
          "type": "op",
          "address": "",
          "percentage": 1
        }
      ],
      "blockRefreshInterval": 90,
      "clientConnectionTimeout": 600,
      "banning": {
        "enabled": true,
        "time": 10,
        "invalidPercent": 50,
        "checkThreshold": 50
      },
      "ports": {
        "7751": {
          "listenAddress": "*",
          "difficulty": 0.25,
          "name": "ASIC MRR",
          "varDiff": {
            "minDiff": 0.25,
            "maxDiff": null,
            "targetTime": 30,
            "retargetTime": 160,
            "variancePercent": 40
          }
        }
      },
      "daemons": [
        {
          "host": "127.0.0.1",
          "port": ,
          "user": "",
          "password": ""
        }
      ],
      "paymentProcessing": {
        "enabled": true,
        "minimumPayment": 0.1,
        "payoutScheme": "SOLO",
        "payoutSchemeConfig": {
          "factor": 0.5
        }
      }
    },
    
    
    Please let me know how I can try to fix this. I can't figure it out.

**Comment by b2d2dbone** [comment]
try changing the share  multiplier in :

miningcore/src/Miningcore/coins.json

 "shareMultiplier": ChangeThisValue increase or decrease OK ,
 
 Good Luck
