### ISSUE TITLE
keep getting interrupted during build

### ISSUE THREAD

**Issue by pool2mine** [xiaolin1579/miningcore#54]
I tried to build in ubuntu 22, and also ubuntu 20... i am looking at 2 errors while console is running script:

```
/usr/lib/gcc/x86_64-linux-gnu/9/include/wmmintrin.h(61,1): error GCC3463B0: inlining failed in call to always_inline ‘_mm_aesenc_si128’: target specific option mismatch [/home/test/miningcore/src/Miningcore/Miningcore.csproj]
     61 | _mm_aesenc_si128 (__m128i __X, __m128i __Y)
        | ^~~~~~~~~~~~~~~~
  In file included from crypto/haraka.c:28:
  crypto/haraka.h:47:8: note: called from here
     47 |   s1 = _mm_aesenc_si128(s1, rc[rci + 1]); \
        |        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  crypto/haraka.c:133:3: note: in expansion of macro ‘AES2’
    133 |   AES2(s[0], s[1], 16);
        |   ^~~~
  In file included from /usr/lib/gcc/x86_64-linux-gnu/9/include/immintrin.h:39,
                   from crypto/haraka.h:29,
                   from crypto/haraka.c:28:
/usr/lib/gcc/x86_64-linux-gnu/9/include/wmmintrin.h(61,1): error GCC3463B0: inlining failed in call to always_inline ‘_mm_aesenc_si128’: target specific option mismatch [/home/test/miningcore/src/Miningcore/Miningcore.csproj]
     61 | _mm_aesenc_si128 (__m128i __X, __m128i __Y)
        | ^~~~~~~~~~~~~~~~
  In file included from crypto/haraka.c:28:
  crypto/haraka.h:46:8: note: called from here
```

and finally the it end up interrupted with this error:

```
/home/test/miningcore/src/Miningcore/Miningcore.csproj(123,9): error MSB3073: The command "(cd /home/test/miningcore/src/Miningcore/ && sh build-libs-linux.sh bin/Release/net6.0/)" exited with code -1.
```

i tried to manually run ./build-libs-linux.sh, it installs dependencies without issues, but when i run the installer script again, same result

**Comment by pool2mine** [comment]
is it just me or is there a problem building this repo? i have tried different fresh ubuntu installations, used the script, installed without script... then i tried to install oliver version and it does get installed without issues, so i am assuming is not a MV problem. i think it's more a dependencies issue. is anyone else having issues to install this repo? I really wanted because there are so many coins added (great work btw). please let me know!

**Comment by pool2mine** [comment]
BTW, The fork on the AIPG github does build without issues, but ironically, it does not have AIPG included on supported coins... i'm not sure if it's just a copy/paste on coins.json (as algo is already included), but i tried that and it does not connect with the blockchain

**Comment by angelloll** [comment]
> BTW, The fork on the AIPG github does build without issues, but ironically, it does not have AIPG included on supported coins... i'm not sure if it's just a copy/paste on coins.json (as algo is already included), but i tried that and it does not connect with the blockchain

if you need help connect my on discord 417534606997192705 or go to getablocks.com for discord link

**Comment by scorpio18** [comment]
> is it just me or is there a problem building this repo? i have tried different fresh ubuntu installations, used the script, installed without script... then i tried to install oliver version and it does get installed without issues, so i am assuming is not a MV problem. i think it's more a dependencies issue. is anyone else having issues to install this repo? I really wanted because there are so many coins added (great work btw). please let me know!

Try to change this in the ~/miningcore/src/Native/libverushash/Makefile first 2 lines, delete $(CPU_FLAGS) and add -maes -mpclmul -mssse3
```
CFLAGS += -g -Wall -c -fPIC -O2 -Wno-pointer-sign -Wno-char-subscripts -Wno-unused-variable -Wno-unused-function -Wno-strict-aliasing -Wno-discarded-qualifiers -Wno-unused-const-variable -maes -mpclmul -mssse3
CXXFLAGS += -g -Wall -fPIC -fpermissive -O2 -faligned-new -Wno-char-subscripts -Wno-unused-variable -Wno-unused-function -Wno-strict-aliasing -Wno-sign-compare -std=c++11 -maes -mpclmul -mssse3
```

**Comment by pool2mine** [comment]
> > is it just me or is there a problem building this repo? i have tried different fresh ubuntu installations, used the script, installed without script... then i tried to install oliver version and it does get installed without issues, so i am assuming is not a MV problem. i think it's more a dependencies issue. is anyone else having issues to install this repo? I really wanted because there are so many coins added (great work btw). please let me know!
> 
> Try to change this in the ~/miningcore/src/Native/libverushash/Makefile first 2 lines, delete $(CPU_FLAGS) and add -maes -mpclmul -mssse3
> 
> ```
> CFLAGS += -g -Wall -c -fPIC -O2 -Wno-pointer-sign -Wno-char-subscripts -Wno-unused-variable -Wno-unused-function -Wno-strict-aliasing -Wno-discarded-qualifiers -Wno-unused-const-variable -maes -mpclmul -mssse3
> CXXFLAGS += -g -Wall -fPIC -fpermissive -O2 -faligned-new -Wno-char-subscripts -Wno-unused-variable -Wno-unused-function -Wno-strict-aliasing -Wno-sign-compare -std=c++11 -maes -mpclmul -mssse3
> ```

Hi @scorpio18 sorry for my late reply, Thank you very much! this actually solved my build problem. Closing now!
