### ISSUE TITLE
SOLO+PPLNS  and 2 algorithms on same coin config .js example 

### ISSUE THREAD

**Issue by b2d2dbone** [xiaolin1579/miningcore#70]
Hi guys 

I need help making config.js for the pool to run both SOLO and PPLNS payment scheme  and using SHA256+SCRYPT 

using the same Digibyte daemon  

what should I use in my digibyte core config file ? 

my config same as  the following : 
  "pools": [{
      "id": "dgb-scrypt",
      "enabled": true,
      "coin": "digibyte-scrypt",
      "address": "DAFtYMGVdNtqHJoBGg2xqZZwSuYAaEs2Bn",
      "rewardRecipients": [
        {
          "address": "DAFtYMGVdNtqHJoBGg2xqZZwSuYAaEs2Bn",
          "percentage": 1.0
        }
      ],
      "blockRefreshInterval": 500,
      "jobRebroadcastTimeout": 10,
      "clientConnectionTimeout": 600,
      "banning": {
        "enabled": true,
        "time": 600,
        "invalidPercent": 50,
        "checkThreshold": 50
      },
      "ports": {
        "3062": {
          "listenAddress": "0.0.0.0",
          "difficulty": 1024,
          "varDiff": {
            "minDiff": 512,
            "targetTime": 15,
            "retargetTime": 90,
            "variancePercent": 30
          }
        }
      },
      "daemons": [
        {
          "host": "127.0.0.1",
          "port": 9998,
          "user": "user",
          "password": "password"
        }
      ],
      "paymentProcessing": {
        "enabled": true,
        "minimumPayment": 0.5,
        "payoutScheme": "PPLNS",
        "payoutSchemeConfig": {
          "factor": 2.0
        }
      }
    }]
}

**Comment by NakulKaul644** [comment]
You can setup 4 different pool Digibyte SHA256 SOLO, Digibyte SHA256 PPLNS, Digibyte SCRYPT SOLO & Digibyte SCRYPT PPLNS

**Comment by b2d2dbone** [comment]
> You can setup 4 different pool Digibyte SHA256 SOLO, Digibyte SHA256 PPLNS, Digibyte SCRYPT SOLO & Digibyte SCRYPT PPLNS. You need to use different pool id for them so they are identifiable. In case you want to show all of them together on website then you need to do make some changes to the UI.

What changes in UI  where exactly ? I only edited website URL and stratum link in miningcore.js

**Comment by NakulKaul644** [comment]
> > You can setup 4 different pool Digibyte SHA256 SOLO, Digibyte SHA256 PPLNS, Digibyte SCRYPT SOLO & Digibyte SCRYPT PPLNS. You need to use different pool id for them so they are identifiable. In case you want to show all of them together on website then you need to do make some changes to the UI.
> 
> What changes in UI where exactly ? I only edited website URL and stratum link in miningcore.js

Do you see 4 differnt pools on index page?

**Comment by NakulKaul644** [comment]
Make 4 different configs
    
    "pools": [{
"id": "dgb-scrypt",
"enabled": true,
"coin": "digibyte-scrypt",
"address": "DAFtYMGVdNtqHJoBGg2xqZZwSuYAaEs2Bn",
"rewardRecipients": [
{
"address": "DAFtYMGVdNtqHJoBGg2xqZZwSuYAaEs2Bn",
"percentage": 1.0
}
],
"blockRefreshInterval": 500,
"jobRebroadcastTimeout": 10,
"clientConnectionTimeout": 600,
"banning": {
"enabled": true,
"time": 600,
"invalidPercent": 50,
"checkThreshold": 50
},
"ports": {
"3062": {
"listenAddress": "0.0.0.0",
"difficulty": 1024,
"varDiff": {
"minDiff": 512,
"targetTime": 15,
"retargetTime": 90,
"variancePercent": 30
}
}
},
"daemons": [
{
"host": "127.0.0.1",
"port": 9998,
"user": "user",
"password": "password"
}
],
"paymentProcessing": {
"enabled": true,
"minimumPayment": 0.5,
"payoutScheme": "PPLNS",
"payoutSchemeConfig": {
"factor": 2.0
}
}
}]
}
"pools": [{
"id": "dgb-scrypt",
"enabled": true,
"coin": "digibyte-scrypt",
"address": "DAFtYMGVdNtqHJoBGg2xqZZwSuYAaEs2Bn",
"rewardRecipients": [
{
"address": "DAFtYMGVdNtqHJoBGg2xqZZwSuYAaEs2Bn",
"percentage": 1.0
}
],
"blockRefreshInterval": 500,
"jobRebroadcastTimeout": 10,
"clientConnectionTimeout": 600,
"banning": {
"enabled": true,
"time": 600,
"invalidPercent": 50,
"checkThreshold": 50
},
"ports": {
"3062": {
"listenAddress": "0.0.0.0",
"difficulty": 1024,
"varDiff": {
"minDiff": 512,
"targetTime": 15,
"retargetTime": 90,
"variancePercent": 30
}
}
},
"daemons": [
{
"host": "127.0.0.1",
"port": 9998,
"user": "user",
"password": "password"
}
],
"paymentProcessing": {
"enabled": true,
"minimumPayment": 0.5,
"payoutScheme": "Solo",
"payoutSchemeConfig": {
"factor": 2.0
}
}
}]
}

"pools": [{
"id": "dgb-sha256",
"enabled": true,
"coin": "digibyte-sha256",
"address": "DAFtYMGVdNtqHJoBGg2xqZZwSuYAaEs2Bn",
"rewardRecipients": [
{
"address": "DAFtYMGVdNtqHJoBGg2xqZZwSuYAaEs2Bn",
"percentage": 1.0
}
],
"blockRefreshInterval": 500,
"jobRebroadcastTimeout": 10,
"clientConnectionTimeout": 600,
"banning": {
"enabled": true,
"time": 600,
"invalidPercent": 50,
"checkThreshold": 50
},
"ports": {
"3062": {
"listenAddress": "0.0.0.0",
"difficulty": 1024,
"varDiff": {
"minDiff": 512,
"targetTime": 15,
"retargetTime": 90,
"variancePercent": 30
}
}
},
"daemons": [
{
"host": "127.0.0.1",
"port": 9998,
"user": "user",
"password": "password"
}
],
"paymentProcessing": {
"enabled": true,
"minimumPayment": 0.5,
"payoutScheme": "PPLNS",
"payoutSchemeConfig": {
"factor": 2.0
}
}
}]
}
"pools": [{
"id": "dgb-sha256",
"enabled": true,
"coin": "digibyte-sha256",
"address": "DAFtYMGVdNtqHJoBGg2xqZZwSuYAaEs2Bn",
"rewardRecipients": [
{
"address": "DAFtYMGVdNtqHJoBGg2xqZZwSuYAaEs2Bn",
"percentage": 1.0
}
],
"blockRefreshInterval": 500,
"jobRebroadcastTimeout": 10,
"clientConnectionTimeout": 600,
"banning": {
"enabled": true,
"time": 600,
"invalidPercent": 50,
"checkThreshold": 50
},
"ports": {
"3062": {
"listenAddress": "0.0.0.0",
"difficulty": 1024,
"varDiff": {
"minDiff": 512,
"targetTime": 15,
"retargetTime": 90,
"variancePercent": 30
}
}
},
"daemons": [
{
"host": "127.0.0.1",
"port": 9998,
"user": "user",
"password": "password"
}
],
"paymentProcessing": {
"enabled": true,
"minimumPayment": 0.5,
"payoutScheme": "SOLO",
"payoutSchemeConfig": {
"factor": 2.0
}
}
}]
}

**Comment by b2d2dbone** [comment]
Hi , Thanks for reply ,  I did  make four pools like for coins  and set  each pool a  unique ID but I did not make 2 pools with same ID like what you suggested the only deference is payment scheme . I will try your way hopefully it works  .

**Comment by b2d2dbone** [comment]
Hi , I got to work but using pool IDs  instead of making 4 deferent  configs I just added unique ID per coin , I am not sure why this did not work for me the last time I tired it , maybe browser cache thing anyway  thank you very much for replies <3
