### ISSUE TITLE
Problem with build on ubuntu 22.04 help

### ISSUE THREAD

**Issue by charlesmigel** [xiaolin1579/miningcore#74]
Hello sir, 

Here is the link its the .cs plugin on Ethereum when will you able to fix it?
https://github.com/xiaolin1579/miningcore/actions/runs/9592377585/job/26450831258)](https://github.com/xiaolin1579/miningcore/actions/runs/9592377585/job/26450831258)

let me know  pls soon as possible 
thanks

**Comment by charlesmigel** [comment]
https://github.com/xiaolin1579/miningcore/tree/dev/src    here

**Comment by goodthebest** [comment]
yes installation is broken @xiaolin1579 please have a look and try to fix it.

**Comment by xiaolin1579** [comment]
There were some issues after merging blackmennewstyle's code, which were not resolved, so I moved to develop in this new git.
https://github.com/Kudaraidee/miningcore
